version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: brickuser
      POSTGRES_PASSWORD: brickpass
      POSTGRES_DB: brickxbrick
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  pgdata:
