import { StyleSheet } from "react-native";

export const captureStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
  },
  header: {
    marginBottom: 26,
  },
  eyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginBottom: 14,
  },
  logoMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E76F35",
  },
  logoMarkInner: {
    width: 12,
    height: 12,
    borderRadius: 4,
    backgroundColor: "#FFFDF9",
    transform: [{ rotate: "-12deg" }],
  },
  eyebrow: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "#B94D22",
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "800",
    letterSpacing: -0.8,
    color: "#2E2823",
  },
  subtitle: {
    maxWidth: 320,
    marginTop: 8,
    fontSize: 16,
    lineHeight: 23,
    color: "#81766D",
  },
  options: {
    gap: 12,
  },
  optionCard: {
    minHeight: 112,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    borderRadius: 20,
    backgroundColor: "#FFFDF9",
    shadowColor: "#6C4B38",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 2,
  },
  optionIcon: {
    width: 58,
    height: 58,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 15,
  },
  optionBody: {
    flex: 1,
    paddingRight: 8,
  },
  optionTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "700",
    color: "#2E2823",
  },
  optionDescription: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: "#81766D",
  },
  chevron: {
    fontSize: 25,
    fontWeight: "300",
    color: "#B7A79A",
  },
  footerHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "auto",
    paddingTop: 28,
    paddingBottom: 4,
    gap: 7,
  },
  footerHintIcon: {
    color: "#E76F35",
    fontSize: 17,
  },
  footerHintText: {
    fontSize: 12,
    lineHeight: 17,
    color: "#9A8D83",
  },
  actionStatus: {
    opacity: 0,
  },
  destination: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  destinationIcon: {
    width: 68,
    height: 68,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
    backgroundColor: "#F4D9C8",
  },
  destinationTitle: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    color: "#2E2823",
  },
  destinationCopy: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 15,
    lineHeight: 22,
    color: "#81766D",
  },
});
